# Generated by Django 5.2.8 on 2025-11-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_tarea_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='estado',
            new_name='completada',
        ),
    ]
